### ISSUE TITLE
Using default ZfcRbac configuration for RBAC

### ISSUE THREAD

**Issue by webdevilopers** [ZF-Commons/ZfcAdmin#26]
I am not sure if the configuration is actually required or even deprecated:
https://github.com/ZF-Commons/ZfcAdmin/blob/master/config/zfcadmin.global.php#L54-64

At least you will still have to add configuration to _ZfcRbac_ to make the content accessible:

``` php
        'guards' => [
            'ZfcRbac\Guard\RouteGuard' => [
                'zfcuser/login' => ['guest'],
                'zfcuser*' => ['user'],
                'zfcadmin*' => ['admin'],
            ]
        ],
```

These additions are similar to the ones you need when using _ZfcUser_ with _ZfcRbac_ see issue https://github.com/ZF-Commons/zfc-rbac/issues/221.

**Comment by akrabat** [comment]
Is this still an issue?

if so, can someone PR it?

**Comment by webdevilopers** [comment]
Sorry, no longer using the project nor the module.
